[build]
  publish = "dist"
  command = "npm run build"

[context.production.environment]
  VITE_API_URL = "https://ioserver.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200